server:
  port: 8080

spring:
 application:
   name: user
 datasource:
   username: 'admin'
   url: jdbc:postgresql://localhost:5432/user
   password: 'abcd1234'
   jpa:
     properties:
       hibernate:
         dialect: org.hibernate.dialect.PostgresSQLDialect
         format_sql: 'true'
     hibernate:
       ddl-auto: update
     show-sql: 'true'